# Generated by Django 6.0 on 2026-03-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_offering_stock_status_trade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='offerings/'),
        ),
        migrations.AlterField(
            model_name='userhashobby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
