# Generated by Django 6.0 on 2026-03-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_offering_photo_alter_userhashobby_user'),
        ('marketplace', '0006_gang_creator'),
    ]

    operations = [
    ]
