# Generated by Django 6.0 on 2026-03-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_merge_20260322_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='photo',
        ),
    ]
