# Generated by Django 6.0 on 2026-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_offering_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='offerings/'),
        ),
    ]
